name = "personal-website"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
not_found_handling = "404-page"
